"""add_bytetrack_and_media_fields

Revision ID: 80f60113d725
Revises: e51ec143c396
Create Date: 2026-09-03 09:49:36.658503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f60113d725'
down_revision: Union[str, None] = 'e51ec143c396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drive_sessions', sa.Column('media_metadata', sa.JSON(), nullable=True))
    op.add_column('raw_detections', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_raw_detections_track_id'), 'raw_detections', ['track_id'], unique=False)
    op.add_column('road_events', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column('road_events', sa.Column('evidence_crop_path', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_road_events_track_id'), 'road_events', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_road_events_track_id'), table_name='road_events')
    op.drop_column('road_events', 'evidence_crop_path')
    op.drop_column('road_events', 'track_id')
    op.drop_index(op.f('ix_raw_detections_track_id'), table_name='raw_detections')
    op.drop_column('raw_detections', 'track_id')
    op.drop_column('drive_sessions', 'media_metadata')
    # ### end Alembic commands ###
