"""initial_schema

Revision ID: e51ec143c396
Revises:
Create Date: 2026-09-03 09:06:08.149528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51ec143c396'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('source_filename', sa.String(length=256), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('processing_state', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_duration_seconds', sa.Float(), nullable=True),
    sa.Column('source_fps', sa.Float(), nullable=True),
    sa.Column('source_width', sa.Integer(), nullable=True),
    sa.Column('source_height', sa.Integer(), nullable=True),
    sa.Column('total_source_frames', sa.Integer(), nullable=True),
    sa.Column('sampled_frames_count', sa.Integer(), nullable=True),
    sa.Column('frames_with_detections', sa.Integer(), nullable=True),
    sa.Column('total_detections_count', sa.Integer(), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('model_provenance', sa.JSON(), nullable=True),
    sa.Column('route_telemetry', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['drive_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_session_id'), 'artifacts', ['session_id'], unique=False)
    op.create_table('road_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('first_seen_seconds', sa.Float(), nullable=False),
    sa.Column('last_seen_seconds', sa.Float(), nullable=False),
    sa.Column('first_frame_index', sa.Integer(), nullable=False),
    sa.Column('last_frame_index', sa.Integer(), nullable=False),
    sa.Column('representative_detection_id', sa.String(length=64), nullable=True),
    sa.Column('representative_confidence', sa.Float(), nullable=False),
    sa.Column('representative_bbox', sa.JSON(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['drive_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_events_review_status'), 'road_events', ['review_status'], unique=False)
    op.create_index(op.f('ix_road_events_session_id'), 'road_events', ['session_id'], unique=False)
    op.create_table('raw_detections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('x_max', sa.Float(), nullable=False),
    sa.Column('y_max', sa.Float(), nullable=False),
    sa.Column('road_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['road_event_id'], ['road_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['drive_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_detections_frame_index'), 'raw_detections', ['frame_index'], unique=False)
    op.create_index(op.f('ix_raw_detections_session_id'), 'raw_detections', ['session_id'], unique=False)
    op.create_index(op.f('ix_raw_detections_timestamp_seconds'), 'raw_detections', ['timestamp_seconds'], unique=False)
    op.create_table('review_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['road_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_event_id'), 'review_actions', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_actions_event_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_raw_detections_timestamp_seconds'), table_name='raw_detections')
    op.drop_index(op.f('ix_raw_detections_session_id'), table_name='raw_detections')
    op.drop_index(op.f('ix_raw_detections_frame_index'), table_name='raw_detections')
    op.drop_table('raw_detections')
    op.drop_index(op.f('ix_road_events_session_id'), table_name='road_events')
    op.drop_index(op.f('ix_road_events_review_status'), table_name='road_events')
    op.drop_table('road_events')
    op.drop_index(op.f('ix_artifacts_session_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('drive_sessions')
    op.drop_table('devices')
    # ### end Alembic commands ###
